stages:
  train:
    cmd: python train.py
    deps:
    - data
    - train.py
    metrics:
      - training_metrics.json:
          cache: false
    plots:
      - training_metrics/scalars:
          cache: false
  evaluate:
    cmd: python evaluate.py
    deps:
    - evaluate.py
    metrics:
    - evaluation.json:
        cache: false    
   
    